### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by Tefnya**
The only thing i'm not sure about is echo display as i wasn't able to find it in game, was it deleted with rest of echo locators? :<

### CODE REVIEW

**Comment by TheDeathlyCow** [comment]
The echo display is in the game, but its sort of hidden. Its an alternate version of the block display that kills itself after a few ticks - its what creates that glowing outline effect when you use the Echo Locator.

**Comment by TheDeathlyCow** [comment]
Let me know if you are ready for this to merge btw.

**Comment by Tefnya** [comment]
Yep, thanks for the explanation) Guess no one is supposed to see the name of this thing anyway, but it is also translated now, ready for merging.

**Comment by TheDeathlyCow** [comment]
I think they can see the name when using /summon or if they look at it with something like Jade installed. Thanks!

**Pull request merged**
